// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-axios';
import type { ReadUserByEmailApiV1UsersEmailUserEmailGetData, ReadUserByEmailApiV1UsersEmailUserEmailGetError, ReadUserByEmailApiV1UsersEmailUserEmailGetResponse } from './types.gen';

export const client = createClient(createConfig());

export class DefaultService {
    /**
     * Read User By Email
     * Get a specific user by email.
     */
    public static readUserByEmailApiV1UsersEmailUserEmailGet<ThrowOnError extends boolean = false>(options: Options<ReadUserByEmailApiV1UsersEmailUserEmailGetData, ThrowOnError>) {
        return (options?.client ?? client).get<ReadUserByEmailApiV1UsersEmailUserEmailGetResponse, ReadUserByEmailApiV1UsersEmailUserEmailGetError, ThrowOnError>({
            ...options,
            url: '/api/v1/users/email/{user_email}'
        });
    }
    
}