// This file is auto-generated by @hey-api/openapi-ts

export type HttpValidationError = {
    detail?: Array<ValidationError>;
};

export type UserPublic = {
    name: string;
    age: number;
};

export type ValidationError = {
    loc: Array<string | number>;
    msg: string;
    type: string;
};

export type ReadUserByEmailApiV1UsersEmailUserEmailGetData = {
    body?: never;
    path?: never;
    query: {
        email: string;
    };
    url: '/api/v1/users/email/{user_email}';
};

export type ReadUserByEmailApiV1UsersEmailUserEmailGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadUserByEmailApiV1UsersEmailUserEmailGetError = ReadUserByEmailApiV1UsersEmailUserEmailGetErrors[keyof ReadUserByEmailApiV1UsersEmailUserEmailGetErrors];

export type ReadUserByEmailApiV1UsersEmailUserEmailGetResponses = {
    /**
     * Successful Response
     */
    200: UserPublic | null;
};

export type ReadUserByEmailApiV1UsersEmailUserEmailGetResponse = ReadUserByEmailApiV1UsersEmailUserEmailGetResponses[keyof ReadUserByEmailApiV1UsersEmailUserEmailGetResponses];